export const DataTmax = [
  {
    id: 1,
    imgNum: 'pj_tmax_3',
    title: "Tmax SuperApp 플랫폼",
    date: "2021.12 ~ 현재",
    web: "PC/Mobile",
    myRole: "PC/Mobile 페이지 마크업, 서비스 연동",
    cTitle: "Tmax SuperApp 플랫폼 구축 프로젝트",
    cCount: "12",
    cStack: "HTML, CSS, JavaScript, React, TypeScript, Styled-components, Wapl-ui",
    cInfo: "SuperApp 플랫폼 마크업 작업과 account 서비스 연동을 맡아서 작업했습니다. 기본적인 로직은 React와 TypeScript로 작성 가능합니다."
  },
  {
    id: 2,
    imgNum: 'pj_tmax_4',
    title: "Tmax Wapl-ui",
    date: "2022.01~2022.03",
    web: "PC/Mobile",
    myRole: "SuperApp 작업에 앞서 공통 UI 컴포넌트를 재사용 가능하게 라이브러리화 하는 작업",
    cTitle: "공통 UI 컴포넌트 Wapl-ui 라이브러리 구축 프로젝트",
    cCount: "8",
    cStack: "HTML, CSS, JavaScript, React, TypeScript, Styled-components, MUI, Storybook",
    cInfo: "SuperApp 작업을 하기 앞서 React+TypeScript로 MUI에 존재하는 컴포넌트는 커스터마이징하고 존재하지 않는 컴포넌트는 직접 만들어 Storybook으로 배포하여 작업자들이 쓰기 쉽게 작업하였습니다."
  },
  {
    id: 3,
    imgNum: 'pj_tmax_6',
    title: "한국과학기술대학교 미팅 앱 수정",
    date: "2022.05 ~ 2022.07",
    web: "PC/Mobile (Responsive 8월 진행 예정)",
    myRole: "기존 마크업 된 PC/Mobile 스타일 수정",
    cTitle: "한국과학기술대학교 미팅 앱 수정 프로젝트",
    cCount: "4",
    cStack: "HTML, CSS, JavaScript, React, Styled-components",
    cInfo: "기존 작업된 한국과학기술대학교 미팅 앱에 새로운 룩을 입히는 작업을 하고 있습니다. 간단한 로직 수정도 직접 하고 있습니다."
  },
  {
    id: 4,
    imgNum: 'pj_tmax_5',
    title: "인사혁신처 미팅 앱 수정",
    date: "2022.06 ~ 진행 중",
    web: "PC/Mobile",
    myRole: "기존 마크업 된 PC/Mobile 스타일 수정",
    cTitle: "인사혁신처 미팅 앱 수정 프로젝트",
    cCount: "4",
    cStack: "HTML, CSS, JavaScript, React, Styled-components",
    cInfo: "기존 작업된 인사혁신처 미팅 앱에 새로운 룩을 입히는 작업을 하고 있습니다. 간단한 로직 수정도 직접 하고 있습니다."
  },
  {
    id: 5,
    imgNum: 'pj_tmax_2',
    title: "Tmax 통합 협업 플랫폼 Tmax WAPL 구축",
    date: "2020.11 ~ 2021.06(30주)",
    web: "PC",
    myRole: "PC 페이지 마크업",
    cTitle: "Tmax WAPL 구축 프로젝트",
    cCount: "13",
    cStack: "HTML, CSS, JavaScript, React, Styled-components",
    cInfo: "React를 사용하여 돔을 컴포넌트화 하고 재사용 하는 방법으로 작업했습니다. 플랫폼 뿐만 아니라 WAPL Talk의 퍼블리싱도 진행하였습니다."
  },
  {
    id: 6,
    imgNum: 'pj_tmax_1',
    title: "Posco 일정관리 플랫폼 Posco Task 구축",
    date: "2020.08 ~ 2020.12(12주)",
    web: "PC/Mobile",
    myRole: "PC/Mobile 페이지 마크업",
    cTitle: "Posco Task 구축 프로젝트",
    cCount: "10",
    cStack: "HTML, CSS, JavaScript",
    cInfo: "Tmax 입사 후 첫 프로젝트입니다. Tmax WAPL안의 Works앱과 동일한 기능으로 slack과 같은 협업 툴입니다."
  },
]

export const DataView3 = [
  {
    id: 1,
    imgNum: 'pj_73',
    title: "성묵 Responsive Web Site 구축",
    date: '2020.04(3주)',
    web: 'PC/Mobile Responsive',
    myRole: 'Responsive 페이지 마크업, 모션(100%)',
    siteURL: 'http://seongmuk.com/',
    gitURL: 'https://github.com/hagoni/seongmuk',
  },
  {
    id: 2,
    imgNum: 'pj_71',
    title: "강강술래 Responsive Web Site 구축",
    date: '2020.02(3주)',
    web: 'PC/Mobile Responsive',
    myRole: 'Responsive 페이지 마크업, 모션(100%)',
    siteURL: 'https://sullai.com/',
    gitURL: 'https://github.com/hagoni/sullai',
  },
  {
    id: 3,
    imgNum: 'pj_49',
    title: "상무초밥 PC/Mobile Web Site 구축",
    date: '2020.02(2주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업, 모션(100%)',
    siteURL: 'https://sangmusushi.kr/',
    gitURL: 'https://github.com/hagoni/sangmusushi',
  },
  {
    id: 4,
    imgNum: 'pj_48',
    title: "마포갈매기 리뉴얼 PC/Mobile Web Site 구축",
    date: '2020.01(3주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업, 모션(100%)',
    siteURL: 'https://www.mapo92.com/',
    gitURL: 'https://github.com/hagoni/mapo92',
  },
  {
    id: 5,
    imgNum: 'pj_47',
    title: "산카이 PC/Mobile Web Site 구축",
    date: '2019.12(3주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업, 모션(100%)',
    siteURL: 'http://sankai.co.kr/',
    gitURL: 'https://github.com/hagoni/sankai',
  },
  {
    id: 6,
    imgNum: 'pj_40',
    title: "감성커피 PC/Mobile Web Site 구축",
    date: '2019.09(3주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업, 모션(100%)',
    siteURL: 'http://www.xn--439as41bv4jv9f.com/',
    gitURL: 'https://github.com/hagoni/gamsungcoffee',
  },
  {
    id: 7,
    imgNum: 'pj_66',
    title: "먹보한우 PC/Mobile landing Web Site 구축",
    date: '2020.04(1주)',
    web: 'PC/Mobile landing',
    myRole: 'PC/Mobile landing 페이지 마크업, 모션(100%)',
    siteURL: 'http://mokbohanwoo.com/landing/',
  },
  {
    id: 8,
    imgNum: 'pj_64',
    title: "임대장 PC/Mobile landing Web Site 구축",
    date: '2020.04(1주)',
    web: 'PC/Mobile landing',
    myRole: 'PC/Mobile landing 페이지 마크업, 모션(100%)',
    siteURL: 'http://xn--vk1b120b4c.com/landing/',
  },
  {
    id: 9,
    imgNum: 'pj_62',
    title: "얼맥당 PC/Mobile landing Web Site 구축",
    date: '2020.03(1주)',
    web: 'PC/Mobile landing',
    myRole: 'PC/Mobile landing 페이지 마크업, 모션(100%)',
    siteURL: 'http://xn--ok1b74k13k.com/landing/',
  },
  {
    id: 10,
    imgNum: 'pj_65',
    title: "육대장 PC/Mobile landing Web Site 구축",
    date: '2020.03(1주)',
    web: 'PC/Mobile landing',
    myRole: 'PC/Mobile landing 페이지 마크업, 모션(100%)',
    siteURL: 'http://yukdaejang.co.kr/landing/',
  },
  {
    id: 11,
    imgNum: 'pj_50',
    title: "공만치킨 PC/Mobile Web Site 구축",
    date: '2020.03(2주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업, 모션(100%)',
    siteURL: 'http://gongman.ivyro.net/',
  },
  {
    id: 12,
    imgNum: 'pj_72',
    title: "아지오디자인 Responsive Web Site 구축",
    date: '2020.01(2주)',
    web: 'PC/Mobile Responsive',
    myRole: 'Responsive 페이지 마크업, 모션(100%)',
    siteURL: 'http://agiodesign.co.kr/',
  },
  {
    id: 13,
    imgNum: 'pj_61',
    title: "크앙분식 PC/Mobile landing Web Site 구축",
    date: '2019.12(1주)',
    web: 'PC/Mobile landing',
    myRole: 'PC/Mobile landing 페이지 마크업, 모션(100%)',
    siteURL: 'http://k-ang.co.kr/landing/',
  },
  {
    id: 14,
    imgNum: 'pj_46',
    title: "프랭크버거 PC/Mobile Web Site 구축",
    date: '2019.12(2주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업, 모션(100%)',
    siteURL: 'http://frankburger.co.kr/',
  },
  {
    id: 15,
    imgNum: 'pj_45',
    title: "PC토랑 PC/Mobile Web Site 구축",
    date: '2019.12(2주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업, 모션(100%)',
    siteURL: 'http://thetorang.com/',
  },
  {
    id: 16,
    imgNum: 'pj_44',
    title: "국밥대장 PC/Mobile Web Site 구축",
    date: '2019.11(2주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업, 모션(100%)',
    siteURL: 'http://xn--3e0bt9hwyir2l.com/',
  },
  {
    id: 17,
    imgNum: 'pj_42',
    title: "방태막국수 PC/Mobile Web Site 구축",
    date: '2019.10(2주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업, 모션(100%)',
    siteURL: 'http://makguksu.kr/',
  },
  {
    id: 18,
    imgNum: 'pj_41',
    title: "땅콩 쉐어하우스 PC/Mobile Web Site 구축",
    date: '2019.10(2주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업, 모션(100%)',
    siteURL: 'http://xn--h11bt90c.net/',
  },
  {
    id: 19,
    imgNum: 'pj_39',
    title: "봉구통닭 PC/Mobile Web Site 구축",
    date: '2019.09(3주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업, 모션(100%)',
    siteURL: 'http://bongguchicken.com/',
  },
  {
    id: 20,
    imgNum: 'pj_38',
    title: "올벤PC방 PC/Mobile Web Site 구축",
    date: '2019.09(2주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업, 모션(100%)',
    siteURL: 'http://allbenpc.ivyro.net/',
  },
  {
    id: 21,
    imgNum: 'pj_70',
    title: "더짱터 PC landing Web Site 구축",
    date: '2019.08(1주)',
    web: 'PC landing',
    myRole: 'PC landing 페이지 마크업(80%)',
    siteURL: 'http://xn--9m1bw24b98e.com/landing/',
  },
  {
    id: 22,
    imgNum: 'pj_37',
    title: "금별맥주 PC/Mobile Web Site 구축",
    date: '2019.08(2주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업, 모션(80%)',
    siteURL: 'http://goldstarbeer.co.kr/',
  },
  {
    id: 23,
    imgNum: 'pj_35',
    title: "한촌설렁탕 리뉴얼 PC/Mobile Web Site 구축",
    date: '2019.07(3주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업, 모션(80%)',
    siteURL: 'http://hanchon.kr/new/',
  },
  {
    id: 24,
    imgNum: 'pj_33',
    title: "청년다방 리뉴얼 PC/Mobile Web Site 구축",
    date: '2019.06(3주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업, 모션(60%)',
    siteURL: 'http://www.youngdabang.com/',
  },
  {
    id: 25,
    imgNum: 'pj_32',
    title: "더진국 리뉴얼 PC/Mobile Web Site 구축",
    date: '2019.05(3주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업, 모션(60%)',
    siteURL: 'http://thejincook.com/',
  },
  {
    id: 26,
    imgNum: 'pj_31',
    title: "하남돼지집 리뉴얼 PC/Mobile Web Site 구축",
    date: '2019.05(3주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업, 모션(60%)',
    siteURL: 'https://hanampig.co.kr/',
  },
  {
    id: 27,
    imgNum: 'pj_29',
    title: "존가네 PC/Mobile Web Site 구축",
    date: '2019.03(1주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업, 모션(50%)',
    siteURL: 'http://johngane.co.kr/',
  },
  {
    id: 28,
    imgNum: 'pj_28',
    title: "미사리 밀빛 초계국수 PC/Mobile Web Site 구축",
    date: '2019.03(2주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업, 모션(70%)',
    siteURL: 'http://xn--989aom652c6jk.kr/',
  },
  {
    id: 29,
    imgNum: 'pj_27',
    title: "코앤타베 PC/Mobile Web Site 구축",
    date: '2019.03(2주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업, 모션(70%)',
    siteURL: 'http://co-tabe.co.kr/',
  },
  {
    id: 30,
    imgNum: 'pj_26',
    title: "와인싸롱 VinVin PC/Mobile Web Site 구축",
    date: '2019.02(2주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업, 모션(70%)',
    siteURL: 'http://xn--op2bn6q8rcx9a.com/',
  },
  {
    id: 31,
    imgNum: 'pj_25',
    title: "이차돌 PC/Mobile Web Site 구축",
    date: '2019.02(3주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업, 모션(70%)',
    siteURL: 'http://2chadol.com/',
  },
  {
    id: 32,
    imgNum: 'pj_24',
    title: "육수당 PC/Mobile Web Site 구축",
    date: '2019.01(2주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업(100%)',
    siteURL: 'http://www.yuksudang.com/',
  },
  {
    id: 33,
    imgNum: 'pj_23',
    title: "경성주막 리뉴얼 PC/Mobile Web Site 구축",
    date: '2019.01(3주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업(100%)',
    siteURL: 'http://ks1929.co.kr/',
  },
  {
    id: 34,
    imgNum: 'pj_21',
    title: "레드문 PC/Mobile Web Site 구축",
    date: '2018.12(3주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업(100%)',
    siteURL: 'http://xn--hy1b43d89c.com/',
  },
  {
    id: 35,
    imgNum: 'pj_20',
    title: "팔도실비집 PC/Mobile Web Site 구축",
    date: '2018.12(2주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업(100%)',
    siteURL: 'http://paldosilbijib.com',
  },
  {
    id: 36,
    imgNum: 'pj_18',
    title: "후룩까스 PC/Mobile Web Site 구축",
    date: '2018.11(2주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업(100%)',
    siteURL: 'http://hurukggas.com/',
  },
  {
    id: 37,
    imgNum: 'pj_54',
    title: "혼밥대장 PC/Mobile landing Web Site 구축",
    date: '2018.10(1주)',
    web: 'PC/Mobile landing',
    myRole: 'PC/Mobile landing 페이지 마크업(50%)',
    siteURL: 'http://honbap.kr/landing/',
  },
  {
    id: 38,
    imgNum: 'pj_16',
    title: "구노포차 PC/Mobile Web Site 구축",
    date: '2018.10(2주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업(100%)',
    siteURL: 'http://www.gunopocha.co.kr/',
  },
  {
    id: 39,
    imgNum: 'pj_15',
    title: "파리공방 PC/Mobile Web Site 구축",
    date: '2018.10(2주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업(100%)',
    siteURL: 'http://parisatelier.co.kr/',
  },
  {
    id: 40,
    imgNum: 'pj_53',
    title: "지금보고싶다 PC/Mobile Web Site 구축",
    date: '2018.09(2주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업(50%)',
    siteURL: 'http://missyou.co.kr/',
  },
  {
    id: 41,
    imgNum: 'pj_14',
    title: "79대포 PC/Mobile Web Site 구축",
    date: '2018.09(2주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업(100%)',
    siteURL: 'http://79daepo.com/',
  },
  {
    id: 42,
    imgNum: 'pj_13',
    title: "가마깨비 PC/Mobile Web Site 구축",
    date: '2018.09(2주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업(70%)',
    siteURL: 'http://gamakkebi.com/',
  },
  {
    id: 43,
    imgNum: 'pj_52',
    title: "투마리나 PC/Mobile landing Web Site 구축",
    date: '2018.08(1주)',
    web: 'PC/Mobile landing',
    myRole: 'PC/Mobile landing 페이지 마크업(50%)',
    siteURL: 'http://twomarina.com/landing/',
  },
  {
    id: 44,
    imgNum: 'pj_9',
    title: "달테이블 PC/Mobile Web Site 구축",
    date: '2018.07(2주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업(100%)',
    siteURL: 'http://daltable.co.kr/',
  },
  {
    id: 45,
    imgNum: 'pj_8',
    title: "고래식당 PC/Mobile Web Site 구축",
    date: '2018.06(2주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업(60%)',
    siteURL: 'http://goraesikdang.co.kr/',
  },
  {
    id: 46,
    imgNum: 'pj_6',
    title: "연안식당 PC/Mobile Web Site 구축",
    date: '2018.06(2주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업(60%)',
    siteURL: 'http://yeonansikdang.co.kr/',
  },
  {
    id: 47,
    imgNum: 'pj_5',
    title: "고래감자탕 PC/Mobile Web Site 구축",
    date: '2018.06(2주)',
    web: 'PC/Mobile',
    myRole: 'PC/Mobile 페이지 마크업(60%)',
    siteURL: 'http://goraegamja.co.kr/',
  },
  {
    id: 48,
    imgNum: 'pj_1',
    title: "브리콘 Mobile Web Site 구축",
    date: '2018.03(2주)',
    web: 'Mobile',
    myRole: 'Mobile 페이지 마크업(100%)',
    siteURL: 'http://ebricon.com/m/',
  },
]